spring.application.name=Franchise_Savior

spring.datasource.url=jdbc.postgresql://localhost:5432/nfl_franchise
spring.datasource.username=postgres
spring.datasource.password=Thebestgamemaker1!
spring.jpa.hibernate.ddl-auto=update
